### PR TITLE
user fiendly

### PR DESCRIPTION
**Pull request by ghost**
1) convert to maven layout; 
2) make completed koan tests work out of the box; 
3) keep H2 sakila database in the project; 
4) add H2 server runner;

### CODE REVIEW

**Comment by quux00** [comment]
Hi carrot-garden - 

Thanks for the work on making this better.  I don't have time to review all the changes today, but I will definitely take a look tomorrow (08-July-2012) - there are a lot of changes to consider :-)

**Comment by ghost** [comment]
Michael:

cool; thanks for considering this.

it's probably be easier for you to clone my fork of your koan to get an overview of changed layout;

Andrei.

**Comment by quux00** [comment]
Hi Andrei,

I spent some time reviewing your changes.  It looks like the main goals are:
1. Put the completed koans into src/test and change the package name of all those completed koans to be in the "test" package.
2. Convert the structure to maven style
3. Bring in H2 and allow you to run the H2 web server and connect to the H2 from MyBatis via TCP (standard JDBC connection).

Did I miss anything?

#### My response

I think #1 is a good idea. In addition to being easier for users, it will simplify testing the solutions when new versions of MyBatis are released.

Converting to maven structure is also something worthwhile. I thought about that when I started, but I don't know Maven well enough to tackle it, so I stayed with ant.  If you will help me with some of issues I list below, we can work on converting this to a maven structure.

H2 is also a good idea - I've never used it and would like to learn.  I was thinking of doing HSQL when I started, but I don't have enough experience, and wanted to focus on MySQL and PostgreSQL first to get everything working.

#### Next Steps

OK - so now the things we need to work on.

First, other than doing mvn compile and mvn test-compile (either command line or in Eclipse), I don't know how to get anything else you've done working.

How does one start the RunH2 class?  I don't see a target for it in the pom and I'm not sure how otherwise to get the classpath set up to run it.

Second, with the new structure, how will a person run a specific koan?  With my original setup, you would type `ant koan11` to run koan11.  What is the equivalent way to do that with maven?  Will we need to write a target?  Should it refer to the ant file?

Third, the ant file is currently broken in your setup.  I would like to keep it working for those that do not like or want to use maven.  

Fourth, we will need to update the main README documentation with clear instructions on how to set it up and run each part, etc.

If we can work on these together, I think we can definitely overhaul the MyBatis koans and make it even better.

_Final note:_ I haven't been doing any active development on my master branch, so you have the latest.  It would probably be best to work on these tasks in your repo and then merge them into mine when it is all working.  Merging it in now would break the current setup for current users.

I'm going to leave this pull request open for now, but probably close it after we decide how we want to proceed.

Thanks again for contributing this,
-Michael

**Comment by ghost** [comment]
Michael:

-------- Original Message --------
Subject: Re: [mybatis-koans] user fiendly (#1)
From: Michael Peterson
reply@reply.github.com
To: Andrei Pozolotin Andrei.Pozolotin@gmail.com
Date: Sun 08 Jul 2012 03:43:55 PM CDT

> Hi Andrei,
> 
> I spent some time reviewing your changes.  
> cool.
> It looks like the main goals are:
> 1. Put the completed koans into src/test and change the package name of all those completed koans to be in the "test" package.
>    yes
> 2. Convert the structure to maven style
>    yes
> 3. Bring in H2 and allow you to run something (the koans I presume) from an embedded H2 web server.
>    yes
>    Did I miss anything?
>    no.

my context is:

I needed to upgrade myself from i-batis 2 to my-batis 3;
I was looking for a broad collection of simple code snippets
that would work out of the box in eclipse + maven environment;

your excellent koans was almost it! :-)

> #### My response
> 
> I think #1 is a good idea. In addition to being easier for users, it will simplify testing the solutions when new versions of MyBatis are released and changes to the codebase is required.
> 
> Converting to maven structure is also something worthwhile. I thought about that when I started, but I don't know Maven well enough to tackle it, so I stayed with ant.
> you can keep both ant and maven
>   If you will help me with some of issues I list below, 
> yes I can help
> we can work on converting this to a maven structure.
> 
> H2 is also a good idea - I've never used it and would like to learn.  I was thinking of doing HSQL when I started, but I don't have enough experience, and wanted to focus on MySQL and PostgreSQL first to get everything working.
> H2 was easiest to adapt to koans thanks to
> https://github.com/maxandersen/sakila-h2
> 
> #### Next Steps
> 
> OK - so now the things we need to work on.
> 
> First, other than doing mvn compile and mvn test-compile (either command line or in Eclipse), I don't know how to get anything else you've done working.
> currently everything is eclipse ide - centric in terms of user interaction

the benefit of conversion to maven is that when student clones and
imports your koans
in eclipse + m2e, all dependencies are there, db is there, server is
there, all just works;

> How does one start the RunH2 class?
> server:

eclipse -> right click RunH2.java -> run as java application;

then proceed to koans:

eclipse -> right click KoanXX.java -> run as unit test;

>   I don't see a target for it in the pom and I'm not sure how otherwise to get the classpath set up to run it.
> I can add that;
> 
> Second, with the new structure, how will a person run a specific koan?  
> eclipse -> right click KoanXX.java -> run as unit test;
> 
> With my original setup, you would type `ant koan11` to run koan11.  What is the equivalent way to do that with maven?  Will we need to write a target?  Should it refer to the ant file?
> we can have all 3 of it:

1) still have generic invocation "ant koan11" based on root build.xml

2) have folder with specific files:

build/run-koan11.ant
build/run-koan11-test.ant
build/run-koan12.ant
build/run-koan12-test.ant
build/...

which can be invoked from
eclipse -> right click run-koan-XX.and -> run as ant build;

or from command line;

3) I can also add goals to pom xml to have similar command line
invocations for maven:

mvn test --activate-profile koan11

> Third, the ant file is currently broken in your setup.  I would like to keep it working for those that do not like or want to use maven.  
> I did not test; sure can fix;
> Fourth, we will need to update the main README documentation with clear instructions on how to set it up and run each part, etc.
> yes
> If we can work on these together, I think we can definitely overhaul the MyBatis koans and make it even better.
> cool
> _Final note:_ I haven't been doing any active development on my master branch, so you have the latest.  
> ok
> It would probably be best to work on these in your repo and then merge them into mine when it is all working.  Merging it in now would break the current setup for current users.
> ok. I added you as "collaborator"; please confirm you can commit to the fork
> https://github.com/carrot-garden/sql_mybatis-koans
> 
> I'm going to leave this pull request open for now, but probably close it after we decide how we want to proceed.
> please file itemized issues and assign them to yourself or me on your repo
> https://github.com/midpeter444/mybatis-koans/issues
> 
> Thanks again for contributing this,
> -Michael
> thank you for your koans; they worked great for me;

I hope you can double their number to cover more cases
as well as add some semblance of an index to locate use cases of
interest quickly

finally, you should have some online site where people can obtain
your official blessing (batis certification) when they complete the
koans :-)

cheers!

Andrei.

**Comment by quux00** [comment]
Andrei - I sent you a couple of emails yesterday (to your gmail account) - did you get them?  There are some open questions we should discuss.  Please email back or put comments in this open issue/pull request.

**Comment by ghost** [comment]
I finally found your emails :-) processing now.

**Pull request merged**
